# Generated by Django 4.2.7 on 2024-01-04 18:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cart', '0003_alter_cart_customer'),
    ]

    operations = [
        migrations.AddField(
            model_name='cartitem',
            name='status',
            field=models.PositiveSmallIntegerField(blank=True, choices=[(0, 'Item Added'), (1, 'Item Removed'), (2, 'Item Checkout')], null=True),
        ),
    ]
